project:
  type: website
  output-dir: docs

website:
  title: "Spotopt-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spotopt
format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css

execute:
  freeze: true  # never re-render during project render

